---
# tasks file for ybdb

# Dependencies
- name: Install dependencies
  yum:
    name:
      - wget
      - curl
      - tar
    state: present
  when: "'nodes' in group_names"


#  NEW: Postgres exporter (DB nodes)
- name: Install Postgres Exporter
  import_tasks: postgres_exporter.yaml
  when: "'nodes' in group_names"

# Node exporter (DB nodes)
- name: Install Node Exporter
  import_tasks: node_exporter.yaml
  when: "'nodes' in group_names"

# ------------------------------
# MONITORING (RUN AFTER CLUSTER)
# ------------------------------

# Prometheus
- name: Install Prometheus
  import_tasks: prometheus.yaml
  when: "'monitoring' in group_names"

# Grafana
- name: Install Grafana
  import_tasks: grafana.yaml
  when: "'monitoring' in group_names"

# Alertmanager
- name: Install Alertmanager
  import_tasks: alertmanager.yaml
  when: "'monitoring' in group_names"

# Blackbox
- name: Install Blackbox Exporter
  import_tasks: blackbox.yaml
  when: "'monitoring' in group_names"

# Cleanup
- name: Remove tar files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/prometheus.tar.gz
    - /tmp/alertmanager.tar.gz
    - /tmp/blackbox.tar.gz