- name: Download postgres exporter
  get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ exporter_version }}/postgres_exporter-{{ exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/postgres_exporter.tar.gz
    mode: '0644'

- name: Extract postgres exporter (only if not exists)
  unarchive:
    src: /tmp/postgres_exporter.tar.gz
    dest: /opt/
    remote_src: yes
  args:
    creates: "{{ exporter_dir }}"

- name: Move binary to /usr/local/bin
  command: mv {{ exporter_dir }}/postgres_exporter /usr/local/bin/postgres_exporter
  args:
    creates: /usr/local/bin/postgres_exporter

- name: Set execute permission
  file:
    path: /usr/local/bin/postgres_exporter
    mode: '0755'

- name: Create postgres_exporter service
  template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
  notify:
    - Reload systemd
    - Restart postgres exporter

- name: Enable and start postgres exporter
  systemd:
    name: postgres_exporter
    enabled: yes
    state: started