---
# tasks file for ybdb

- name: Install dependencies (RHEL)
  yum:
    name:
      - wget
      - curl
      - tar
    state: present

# Install Node Exporter ONLY on DB nodes
- name: Install Node Exporter
  import_tasks: node_exporter.yaml
  when: "'nodes' in group_names"

# Install Prometheus ONLY on monitor
- name: Install Prometheus
  import_tasks: prometheus.yaml
  when: "'monitoring' in group_names"

# Install Grafana ONLY on monitor
- name: Install Grafana
  import_tasks: grafana.yaml
  when: "'monitoring' in group_names"

# Install Alertmanager ONLY on monitor

- name: Install Alertmanager
  import_tasks: alertmanager.yaml
  when: "'monitoring' in group_names"

# Install Blackbox Exporter ONLY on monitor
- name: Install Blackbox Exporter
  import_tasks: blackbox.yaml
  when: "'monitoring' in group_names"