---
- name: YugabyteDB Installation
  hosts: all
  gather_facts: true
  become: yes

  vars:
    yugabyte_user: cloud-user
    yugabyte_group: cloud-user
    yugabyte_version: "2025.2.2.0"
    yugabyte_tar: "yugabyte-2025.2.2.0-b80-linux-x86_64.tar.gz"

  tasks:

    - name: Install wget
      ansible.builtin.yum:
        name: wget
        state: present

    - name: Download YugabyteDB tarball
      ansible.builtin.get_url:
        url: "https://software.yugabyte.com/releases/{{ yugabyte_version }}/{{ yugabyte_tar }}"
        dest: "/home/{{ yugabyte_user }}/{{ yugabyte_tar }}"
        mode: '0644'

    - name: Extract YugabyteDB tarball
      ansible.builtin.unarchive:
        src: "/home/{{ yugabyte_user }}/{{ yugabyte_tar }}"
        dest: "/home/{{ yugabyte_user }}/"
        remote_src: yes

    - name: Fix Yugabyte directory ownership
      ansible.builtin.file:
        path: "/home/{{ yugabyte_user }}/yugabyte-{{ yugabyte_version }}"
        owner: "{{ yugabyte_user }}"
        group: "{{ yugabyte_group }}"
        recurse: yes

    - name: Run Yugabyte post install
      ansible.builtin.command: ./bin/post_install.sh
      args:
        chdir: "/home/{{ yugabyte_user }}/yugabyte-{{ yugabyte_version }}"
      become_user: "{{ yugabyte_user }}"

    - name: Deploy yugabyte systemd service
      ansible.builtin.template:
        src: yugabyte.service.j2
        dest: /etc/systemd/system/yugabyte.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable yugabyte service on boot
      ansible.builtin.systemd:
        name: yugabyte.service
        enabled: yes