---
- name: YugabyteDB Installation
  hosts: all
  gather_facts: true
  become: yes
  vars:
    yugabyte_user: cloud-user
    yugabyte_group: cloud-user

  tasks:

    - name: Install wget
      ansible.builtin.yum:
        name: wget
        state: present
      register: install_wget

    - name: print install_wget
      ansible.builtin.debug:
        msg: "{{ install_wget }}"

    - name: Download YugabyteDB tarball
      ansible.builtin.get_url:
        url: "https://software.yugabyte.com/releases/2024.2.2.2/yugabyte-2024.2.2.2-b2-linux-x86_64.tar.gz"
        dest: "/home/cloud-user/yugabyte-2024.2.2.2-b2-linux-x86_64.tar.gz"
        mode: '0644'
      register: ybdb

    - name: Print ybdb 
      ansible.builtin.debug:
        msg: "{{ ybdb }}"
    

    - name: Extract YugabyteDB tarball
      ansible.builtin.unarchive:
        src: "/home/cloud-user/yugabyte-2024.2.2.2-b2-linux-x86_64.tar.gz"
        dest: "/home/cloud-user/"
        remote_src: yes
      register: extract
    
    - name: Extract ybdb 
      ansible.builtin.debug:
        msg: "{{ extract }}"

    - name: Change ownership of entire YugabyteDB directory
      ansible.builtin.file:
        path: "/home/cloud-user/yugabyte-2024.2.2.2"
        owner: cloud-user
        group: cloud-user
        recurse: yes
      register: chown_yugabyte_dir

    - name: Print directory ownership change result
      ansible.builtin.debug:
        msg: "{{ chown_yugabyte_dir }}"


    - name: Run post_install.sh
      ansible.builtin.command: ./bin/post_install.sh
      args:
        chdir: "/home/cloud-user/yugabyte-2024.2.2.2"
      register: post_install

    - name: Print the post_install 
      ansible.builtin.debug:
        msg: "{{ post_install }}"
    


    - name: Deploy yugabyte systemd service using template
      ansible.builtin.template:
        src: yugabyte.service.j2
        dest: /etc/systemd/system/yugabyte.service
        owner: root
        group: root
        mode: '0644'
      register: yugaService
    
    - name: Print yugaService  
      ansible.builtin.debug:
        msg: "{{ yugaService }}"


    - name: Run systemctl daemon_reexec
      command: systemctl daemon-reexec
      register: daemon_reexec

    - name: daemon-reexec
      ansible.builtin.debug:
        msg: "{{ daemon_reexec }}"

    - name: Reload systemd manager configuration
      command: systemctl daemon-reload
      register: daemon_reload

    - name: daemon-reload
      ansible.builtin.debug:
        msg: "{{ daemon_reload }}"

    - name: Enable yuga.service to start at boot
      systemd:
        name: yugabyte.service
        enabled: yes
      register: enable_service
    
    - name: Enable service
      ansible.builtin.debug:
        msg: "{{ enable_service }}"


    - name: Start yuga.service
      systemd:
        name: yugabyte.service
        state: started
      register: start_service

    - name: start service
      ansible.builtin.debug:
        msg: "{{ start_service }}"
    

    - name: Check status of yuga.service
      command: systemctl status yugabyte.service
      register: service_status
      # ignore_errors: yes

    - name: Display service status output
      debug:
        var: service_status.stdout_lines

    - name: Manually check the yugbaytedb 
      command: /home/cloud-user/yugabyte-2024.2.2.2/bin/yugabyted status 
      register: manual_status
    
    - name: print the manual_status
      ansible.builtin.debug:
        msg: "{{ manual_status.stdout_lines }}"

        



# working 