; [monitoring]
; monitor ansible_host=10.0.0.15 ansible_user=ansible

; [nodes]
; node1 ansible_host=10.0.0.10 ansible_user=ansible region=region1 zone=zone1
; node2 ansible_host=10.0.0.11 ansible_user=ansible region=region2 zone=zone2

; node3 ansible_host=10.0.0.12 ansible_user=ansible region=region3 zone=zone1
; node4 ansible_host=10.0.0.13 ansible_user=ansible region=region4 zone=zone2

; node5 ansible_host=10.0.0.14 ansible_user=ansible region=region5 zone=zone1


; [dbs]
; node1 ansible_host=10.0.0.10 ansible_user=ansible
; node2 ansible_host=10.0.0.11 ansible_user=ansible
; node3 ansible_host=10.0.0.12 ansible_user=ansible
; node4 ansible_host=10.0.0.13 ansible_user=ansible
; node5 ansible_host=10.0.0.14 ansible_user=ansible

; Even Better if i already ssh / logged in.
; [monitoring]
; 10.0.0.14

; [nodes]
; 10.0.0.10
; 10.0.0.11
; 10.0.0.12

; [all:vars]
; ansible_user=ansible


[monitoring]
monitor ansible_host=10.0.0.15 ansible_user=ansible

[nodes]
node1 ansible_host=10.0.0.10 ansible_user=ansible region=region1 zone=zone1
node2 ansible_host=10.0.0.11 ansible_user=ansible region=region2 zone=zone2
node3 ansible_host=10.0.0.12 ansible_user=ansible region=region3 zone=zone3

[dbs]
node1
node2
node3

[all:vars]
ansible_user=ansible

[yugabyte_nodes]
ybdb1 ansible_host=10.0.0.10
ybdb2 ansible_host=10.0.0.11
ybdb3 ansible_host=10.0.0.12

[yugabyte_nodes:vars]
ansible_user=yugabyte


[db_nodes]
ybdb1 ansible_host=10.0.0.10 ansible_user=ansible
ybdb2 ansible_host=10.0.0.11 ansible_user=ansible
ybdb3 ansible_host=10.0.0.12 ansible_user=ansible
