[monitoring]
monitor ansible_host=10.0.0.14 ansible_user=ansible

[nodes]
node1 ansible_host=10.0.0.10 ansible_user=ansible
node2 ansible_host=10.0.0.11 ansible_user=ansible
node3 ansible_host=10.0.0.12 ansible_user=ansible

; Even Better if i already ssh / logged in.
; [monitoring]
; 10.0.0.14

; [nodes]
; 10.0.0.10
; 10.0.0.11
; 10.0.0.12

; [all:vars]
; ansible_user=ansible