- name: Setup Monitoring Stack
  hosts: monitor   # or your group name
  become: yes

  roles:
    - monitoring

- name: Setup Monitoring Stack
  hosts: nodes   # or your group name
  become: yes

  roles:
    - monitoring