---
# handlers file for ybdb

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted

#  ADD THIS
- name: Reload systemd
  command: systemctl daemon-reload

#  ADD THIS
- name: Restart Alertmanager
  systemd:
    name: alertmanager
    state: restarted