[ req ]
prompt=no
distinguished_name = my_distinguished_name

[ my_distinguished_name ]
organizationName = Yugabyte
commonName = 10.0.0.11

[ req_ext]
subjectAltName = @alt_names

[alt_names]
IP.1 = 10.0.0.10
IP.2 = 10.0.0.11
IP.3 = 10.0.0.12